# Generated by Django 5.0.2 on 2024-02-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_customuser_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
